vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        ingredientCat:
            uri_prefix: /category/ingredients
            upload_destination: '%kernel.project_dir%/public/category/ingredients'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        recipeCat:
            uri_prefix: /category/recipes
            upload_destination: '%kernel.project_dir%/public/category/recipes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        avatar:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        ingredient:
            uri_prefix: /ingredients
            upload_destination: '%kernel.project_dir%/public/ingredients'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        recipe_pic:
            uri_prefix: /recipes
            upload_destination: '%kernel.project_dir%/public/recipes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
